### ISSUE TITLE
计算geohash的九宫格的结果是错的。

### ISSUE THREAD

**Issue by xbzh** [freeeyes/geohash#2]
计算geohash的九宫格的结果是错的。
//上
sprintf(obj_Geo_Neighbors.m_szNerghbors[1], "%s", Encode((obj_Geo_Rect.m_dMaxLatitude + 
    obj_Geo_Rect.m_dMinLatitude)/2 +(**obj_Geo_Rect.m_dMaxLongitude -** **obj_Geo_Rect.m_dMinLongitude**),
          (obj_Geo_Rect.m_dMaxLongitude + obj_Geo_Rect.m_dMinLongitude)/2,  nPrecision));

应该是：
sprintf(obj_Geo_Neighbors.m_szNerghbors[1], "%s", Encode((obj_Geo_Rect.m_dMaxLatitude + 
    obj_Geo_Rect.m_dMinLatitude)/2 + (**obj_Geo_Rect.m_dMaxLatitude - obj_Geo_Rect.m_dMinLatitude**),
          (obj_Geo_Rect.m_dMaxLongitude + obj_Geo_Rect.m_dMinLongitude)/2,  nPrecision));

其他几个方向的块也有这个问题。

**Comment by freeeyes** [comment]
谢谢，我看一下。
另外，你能给我一个测试用例吗？我可以详细的测试一下。
方便的话，请提交一个pr吧，谢谢。

**Comment by freeeyes** [comment]
你说的对。
我已更新，请帮我测试一下。

**Comment by xbzh** [comment]
测试没问题，但和注释没对上，我添加了评论，你看看。

**Comment by freeeyes** [comment]
恩，我换一下注释。
